### ISSUE TITLE
Missing source folder

### ISSUE THREAD

**Issue by idezigns** [profgyuri/Listen2MeRefined#54]
Cannot build the solution, you're missing

..\Source\My Utils\Source\Source\Source.csproj

**Comment by profgyuri** [comment]
Sorry for the inconvinience, I will remove this dependency later today.

If you want to build the solution before that, please download the source code for my [Source project](https://github.com/profgyuri/Source), add as existing project to the Listen2Me solution, and make sure you add the references where necessary.

**Comment by profgyuri** [comment]
Updated the code so now it does not need the Source project. If you find any bugs, don't be afraid to create a new issue, or even make a PR by yourself, if you feel like contributing :)
